name: Build main

on:
  push:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  REPO: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: downcase REPO
        run: |
          echo "IMAGE_NAME=${REPO,,}" >>${GITHUB_ENV}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Setup docker
        uses: docker/setup-buildx-action@v1
      - name: Login to docker hub
        uses: docker/login-action@v1 
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:main
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.GITHUB_TOKEN }}
          build-args: |
            COMMITSHA=${{ github.sha }}
